service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:775200534168:table/TodoTable

resources: 
  Resources: 
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH

functions:
  addTodo:
    handler: src/addTodo.handler
    events: 
      - httpApi: 
          path: /addTodo
          method: post

  updateTodo:
    handler: src/updateTodo.handler
    events: 
      - httpApi: 
          path: /updateTodo/{id}
          method: put
  
  fetchTodo:
    handler: src/fetchTodo.handler
    events: 
      - httpApi: 
          path: /fetchTodo/{id}
          method: get
  
  fetchTodos:
    handler: src/fetchTodos.handler
    events: 
      - httpApi: 
          path: /fetchTodos
          method: get
  